service: vizio-smartcast-alexa-skill

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: eu-west-1
  environment:
    API_BASE_URL: ${file(./env.json):apiBaseUrl}
    API_SECRET: ${file(./env.json):apiSecret}

package:
 exclude:
  - .git
  - .gitignore
  - README.md

functions:
  index:
    handler: handler.index
    events:
      - alexaSkill